baseUrl=https://demoqa.com/
fullName=Priya Das
gmail=priya123@gmail.com
currAdd=Pune
perAdd=Gadchiroli

//WebTable
firstName=abc
lastName=xyz
userEmail=abc@gmail.com
userAge=25
userSalary=2000
userDepartment=IT


//Forms
firstName=Priya
lastName=Das
gmailForms=priya1@gmail.com
number=8748938739
subject=IT
image=C:\\Users\\DELL\\Downloads\\WhatsApp Image 2025-03-07 at 11.28.33 PM (1).jpeg
currAddForms=Pune